{
 "title": "Dashboard Row",
 "panels": [
  {
   "title": "Virtual Users",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "errors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checks Per Second",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_check",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "check" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "$Measurement",
 "panels": [
  {
   "title": "$Measurement (mean)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM $Measurement WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (max)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (med)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"value\") FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (min)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"value\") FROM $Measurement WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p90)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 90) FROM $Measurement WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (p95)",
   "type": "singlestat",
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"value\", 95) FROM $Measurement WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "graph",
   "description": "Grouped by 1 sec intervals",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT max(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 95) FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "p90",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT percentile(\"value\", 90) FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT min(\"value\") FROM /^$Measurement$/ WHERE $timeFilter and value > 0 GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$Measurement (over time)",
   "type": "heatmap",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT \"value\" FROM $Measurement WHERE $timeFilter and value > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Dashboard Row",
 "panels": []
}
{
 "title": "Micromind Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Quote Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(my_group_zen_service_request_count{method=\"quote\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Question Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(my_group_zen_service_request_count{method=\"question\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "MIcromind Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "my_group_zen_service_request_count"
    }
   ]
  }
 ]
}