apiVersion: v1
data:
  grafana-datasource.yml: |-
    apiVersion: 1

    datasources:
      - name: k6influxdb
        type: influxdb
        access: proxy
        database: k6
        url: http://influxdb:8086
        isDefault: false
      - name: micromind-metrics
        type: prometheus
        url: http://prometheus:9090
        access: server
        isDefault: true
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana-cm2
