apiVersion: v1
data:
  1mongo-init.js: |-
    db.createCollection("quotes", { capped: false });
    db.createCollection("questions", {capped: false});
  2mongo-init.sh: |2-
    #!/bin/bash

    echo "########### Loading data to Quotes Mongo DB Collection ###########"
    mongoimport --jsonArray --db micromind --collection quotes --file /tmp/data/quotes.json


    #!/bin/bash

    echo "########### Loading data to Questions Mongo DB Collection ###########"
    mongoimport --jsonArray --db micromind --collection questions --file /tmp/data/questions.json
kind: ConfigMap
metadata:
  labels:
    app: mongodb
  name: mongodb-cm0
