{
 "title": "Micromind Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Quote Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(my_group_zen_service_request_count{method=\"quote\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Question Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(my_group_zen_service_request_count{method=\"question\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "MIcromind Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "my_group_zen_service_request_count"
    }
   ]
  }
 ]
}